version: '3.8'

services:
  web:
    build: ./scrapper_form
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: offers_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
